### ISSUE TITLE
1.21 Comparator retains power from empty shulker box

### ISSUE THREAD

**Issue by AlxTray** [jellysquid3/Lithium#524]
### Version Information

lithium-fabric-mc1.21-0.12.5

### Expected Behavior

The comparator reading the shulker box should not output a signal if the shulker box is empty

### Actual Behavior

Sometimes when using a box unloader once the shulker box has been drained of all it's items, the comparator reading the box retains powered with a signal strength of 1. This does not occur without the mod, granted this has not been extensively tested but it usually breaks after 2 or 3 shulkers through the unloader and has not happened yet in Vanilla.

### Reproduction Steps

Not exactly 100% sure as I have only tested using a particular box unloader but other than that place a comparator facing away from a shulker box and then empty it, sometimes the empty shulker box will still have a signal strength of 1 read from it.

### Other Information

Tested on a private fabric server running Lithium, FerriteCore, C2ME, Bluemap, Jade, No-enderman-grief, and Spark

**Comment by 2No2Name** [comment]
Cannot reproduce. Tested with only lithium installed, placing a bunch of hoppers, comparators reading the block above the hopper, then placing a shulker box with a few items inside already on top of the hopper, allowing the comparator to read it. After a while all comparators turn off.

**Comment by 2No2Name** [comment]
Maybe test this with and without the other mods to rule out any mod incompatibilities. Otherwise please provide the exact setup (e.g. world download) where the issue shows up

**Comment by Shoftie03** [comment]
I have tested this on both Lithium 1.20.6-0.12.4 and 1.21-0.12.5, running on Prism Launcher Java 21 and can reproduce this issue. The comparator will not update even if the shulker box is empty until a block update is given to it.
https://youtu.be/CQjt4UU92U8 -> where I was able to reproduce this issue
https://youtu.be/9eHcvMi7HUw?si=_d4eJpfItmNGNqeA -> Rapscallion's latest CartMIS sorter, I was able to reproduce this issue in the wdl given: the comparator for the shulker unloader at -2 -46 22 won't update

edit: no other mods aside from lithium present, and issue can be reproduced even without tick sprinting

**Comment by 2No2Name** [comment]
Confirmed by using the Rapscalliion world download at the location with 10+ fully filled boxes in the nearby chest

**Comment by AlxTray** [comment]
That's interesting as the unloader I was facing the issue on was for the CartMIS V2 (https://www.youtube.com/watch?v=LPshwkDboXk). Which the unloader for the CartMIS V3 (the video linked above) uses a very similar or the same unloader for the input. I have just tested on a fresh download of CartMIS V2 and can reproduce again (with only Lithium on my client).

I also had a look at the Storage Tech discord earlier and someone is also facing this issue with the CartMIS V3.

**Comment by AlxTray** [comment]
Additionally, I went back onto the server with Lithium installed with the unloader in a state with a powered comparator from an empty shulker box and no matter how many times I removed and replaced the comparator it would be powered, this was even retained on a server restart. But after removing Lithium and restarting replacing the comparator is de-powered and was fixed.

**Comment by 2No2Name** [comment]
After some more testing I think my attempt to reproduce the issue was broken, because I assumed the empty box shouldn't stay there no matter the comparator state. Can't reproduce in further testing

**Comment by 2No2Name** [comment]
@Shoftie03 is your video recorded in singleplayer with only lithium installed, or is it on a server? If it is on a server, which mods are installed on the server?

**Comment by Shoftie03** [comment]
It is in a singleplayer save of the exact world download in rapscallion's video. I deleted the previous save which I had accessed previously with tweakeroo to unzip a new one, and could still reproduce the issue.

**Comment by 2No2Name** [comment]
What are you putting into the shulker boxes, are you putting them into the storage hall's input chest?

**Comment by Shoftie03** [comment]
I used the sample hermitcraft boxes provided in the outskirts of the wdl (I think I used Grian's set). I nbt copied the barrels, placed them down and put them manually into the input chest inside the hall. Initially I observed the issue with carpet creativeNoClip and thought it was something to do with collision but that's probably irrelevant.

**Comment by 2No2Name** [comment]
Thank you very much, reproduced for sure now

**Comment by AlxTray** [comment]
Are you two only unloading fully-filled shulkers? As I'm attempting to re-produce using half-filled shulkers and I am not getting the issue. So possibly this only occurs when draining full shulkers to empty?

**Comment by 2No2Name** [comment]
This probably requires different item types, with some hopper minecarts not being able to pull items due to the different item type

**Comment by 2No2Name** [comment]
https://github.com/CaffeineMC/lithium-fabric/commit/1f97499aba9de341f762014add948a3db657ca07

**Comment by Shoftie03** [comment]
I am consistently able to reproduce this issue with a full shulkers of non-stackable, not with 16 or 64 stackables

edit: but seems like 2no2name has already resolved this issue; thank you very much!!

**Comment by 2No2Name** [comment]
Workaround: Add line to config/lithium.properties file:
`mixin.block.hopper=false`

**Comment by AlxTray** [comment]
Nice! Thanks for your work in fixing it.
